[project]
name = "obfuse"
version = "0.1.0"
description = "A filesystem that obfuscates the location of all files inside a directory"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fuse-python>=1.0.9",
    "pycryptodome>=3.23.0",
]
